<a href="https://colab.research.google.com/github/shivaveeravalli/sample-programs/blob/main/Sample_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git --version


git version 2.34.1


1.Hardcoding Variables

In [ ]:
# version1_hardcoded.py

a = 10
b = 5_
sum_result = a + b
product_result = a * b

print("Hardcoded Values:")
print("Sum:", sum_result)
print("Product:", product_result)


Hardcoded Values:
Sum: 15
Product: 50


2.Keyboard Input

In [ ]:
# version2_keyboard_input.py

try:
    a = int(input("Enter first number: "))
    b = int(input("Enter second number: "))

    print("Sum:", a + b)
    print("Product:", a * b)

except ValueError:
    print("Error: Please enter valid integers.")


Enter first number: 9
Enter second number: 9
Sum: 18
Product: 81


3. Create a random array of numbers between 0 & 10 and an array of ones

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
import numpy as np

# Random array of shape (3, 3) with values between 0 and 10
random_array = np.random.uniform(0, 10, (3, 3))

# Array of ones of shape (3, 3)
ones_array = np.ones((3, 3))

print("Random Array:")
print(random_array)

print("\nOnes Array:")
print(ones_array)



# both of size (3, 5), save them both to variables
import numpy as np

# Random array with values between 0 and 10
random_array = np.random.uniform(0, 10, (3, 5))

# Array of ones
ones_array = np.ones((3, 5))

# Display the arrays
print("Random Array:\n", random_array)
print("\nOnes Array:\n", ones_array)


Random Array:
[[7.88161236 0.33878221 2.83125773]
 [7.2875669  5.50398773 7.3000772 ]
 [2.36950479 6.3701863  5.63647491]]

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random Array:
 [[4.36209853 7.03908226 7.07101454 3.82881544 2.68614684]
 [5.71932333 8.66669673 0.1108161  3.33431377 9.43978737]
 [9.95460369 1.2373777  0.08461841 9.49142675 4.30215997]]

Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
4.Simple Calculator

In [ ]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Enter first number: 20
Enter second number: 9
Addition: 29
Subtraction: 11
Multiplication: 180
Division: 2.2222222222222223


5.Monkey banana problem

In [ ]:
# Monkey Banana Problem - Simple Version

monkey_position = "floor"
box_position = "corner"
banana_position = "ceiling"
has_banana = False

print("Initial State:")
print("Monkey on floor, box in corner, banana on ceiling")

# Step 1: Move monkey to box
print("\nMonkey moves to the box")
box_position = "under banana"

# Step 2: Push box under banana
print("Monkey pushes the box under the banana")

# Step 3: Climb the box
print("Monkey climbs the box")
monkey_position = "on box"

# Step 4: Grab banana
if monkey_position == "on box" and box_position == "under banana":
    has_banana = True
    print("Monkey grabs the banana 🍌")

print("\nGoal Achieved:", has_banana)


Initial State:
Monkey on floor, box in corner, banana on ceiling

Monkey moves to the box
Monkey pushes the box under the banana
Monkey climbs the box
Monkey grabs the banana 🍌

Goal Achieved: True


In [ ]:
6.Create a 1-dimensional NumPy array using np.array()

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
arr = np.array([1,2,3,4,5])
print(arr)


# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3],[2,4,5]])
print(arr2)



# Create a 3-dimensional Numpy array using np.array()
arr3 =  np.array([[[1,2,3],[2,4,5]],[[1,2,3],[2,4,5]]])
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [2 4 5]]
[[[1 2 3]
  [2 4 5]]

 [[1 2 3]
  [2 4 5]]]


7.Vacuum Cleaner Agent Program

In [ ]:
# Vacuum Cleaner Agent Program

room_A = "Dirty"
room_B = "Dirty"
vacuum_location = "A"

print("Initial State:")
print("Room A:", room_A)
print("Room B:", room_B)
print("Vacuum Location:", vacuum_location)

# If vacuum is in Room A
if vacuum_location == "A":
    if room_A == "Dirty":
        print("\nCleaning Room A...")
        room_A = "Clean"
    print("Moving to Room B")
    vacuum_location = "B"

# If vacuum is in Room B
if vacuum_location == "B":
    if room_B == "Dirty":
        print("\nCleaning Room B...")
        room_B = "Clean"

print("\nFinal State:")
print("Room A:", room_A)
print("Room B:", room_B)
print("Vacuum Cleaner Task Completed 🧹")


Initial State:
Room A: Dirty
Room B: Dirty
Vacuum Location: A

Cleaning Room A...
Moving to Room B

Cleaning Room B...

Final State:
Room A: Clean
Room B: Clean
Vacuum Cleaner Task Completed 🧹


8.Water jug problem

In [ ]:
A, B = 0, 0
capA, capB = 4, 3

B = capB
A = B
B = capB
A = capA
B = 2

print("Jug A:", A)
print("Jug B:", B)
print("Goal achieved")


Jug A: 4
Jug B: 2
Goal achieved


9.Check Even or Odd

In [ ]:
num = int(input("Enter a number: "))
if num % 2 == 0:
    print("Number is Even")
else:
    print("Number is Odd")
print("Check completed")


Enter a number: 9
Number is Odd
Check completed


10.Find Largest of Two Numbers

In [ ]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
if a > b:
    print("Largest:", a)
else:
    print("Largest:", b)
print("Program finished")


Enter first number: 10
Enter second number: 20
Largest: 20
Program finished


11.Sum of First N Numbers

In [ ]:
n = int(input("Enter a number: "))
total = 0
for i in range(1, n + 1):
    total += i
print("Sum:", total)
print("Done")


Enter a number: 20
Sum: 210
Done


12.Count Digits in a Number

In [ ]:
num = int(input("Enter a number: "))
count = 0
while num > 0:
    count += 1
    num //= 10
print("Digits:", count)
print("End")


Enter a number: 129999
Digits: 6
End


13.Palindrome

In [ ]:
word = input("Enter a word: ")
rev = word[::-1]
if word == rev:
    print("Palindrome")
else:
    print("Not Palindrome")
print("Done")


Enter a word: 1331
Palindrome
Done


14.Count Vowels

In [ ]:
text = input("Enter text: ")
vowels = "aeiouAEIOU"
count = 0
for ch in text:
    if ch in vowels:
        count += 1
print("Vowels:", count)
print("Finished")


Enter text: animals
Vowels: 3
Finished


15.Check Prime Number

In [ ]:
num = int(input("Enter a number: "))
flag = True

for i in range(2, num):
    if num % i == 0:
        flag = False
        break

if flag and num > 1:
    print("Prime Number")
else:
    print("Not a Prime Number")


Enter a number: 14
Not a Prime Number
